sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "node"
  - "10"
script: "yarn run test-travis"
before_script:
  - mysql -u root -e 'CREATE DATABASE ircbot;'
  - mysql -u root -e "CREATE USER 'ircbot'@'localhost' IDENTIFIED BY 'ircbot';"
  - mysql -u root -e "GRANT ALL ON ircbot.* TO 'ircbot'@'localhost';"
after_success:
  - codacy-coverage < lcov.info
  - yarn run semantic-release
  - yarn run changelog
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - CXX=g++-4.8
addons:
  mariadb: '10.0'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
