language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
script: "npm run test-travis"
after_success:
  - codacy-coverage < lcov.info
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
